name: learnsphere
description: "A new Flutter project."

flutter_launcher_name:
  name: "LearnSphere"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # TensorFlow Lite (Replaced `tflite` with `tflite_flutter`)
  tflite_flutter: ^0.11.0
  # tflite_flutter_helper: ^0.5.0  # Optional helper functions for image processing
  
  # Local Database & File Handling
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_pdfview: ^1.4.0

  # UI & Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/models/mobilebert.tflite

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/app_icon.JPG"
