name: learnsphere
description: "A new Flutter project."

flutter_launcher_name:
  name: "LearnSphere"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.1.2
  sqflite: ^2.3.0
  path_provider: ^2.0.12
  flutter_pdfview: ^1.4.0
  path: ^1.8.3
  

  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter:

 
  uses-material-design: true
  assets:
    - assets/models/mobilebert.tflite
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/app_icon.JPG"